name: Deploy to VNPT Cloud

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VNPT_HOST }}
          username: ${{ secrets.VNPT_USER }}
          password: ${{ secrets.VNPT_PASS }}
          port: 22
          script: |
            cd /root/Tool-Calendar || exit 1
            docker system prune -a -f --volumes
            git fetch origin develop
            git reset --hard origin/develop
            docker compose build official-doc-backend
            docker rm -f doc-coordination-system || true
            docker compose up -d official-doc-backend
            docker exec nginx-proxy nginx -s reload || docker restart nginx-proxy
